# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    format_listener:
        rules:
            - { path: '^/api/news/', prefer_extension: true, fallback_format: json, priorities: [ json ] }
            - { path: '^/', stop: true }
    view:
        view_response_listener:
            enabled: true
