version: '3.2'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8000:80
    volumes:
      - ./:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:7.2-fpm-alpine
    volumes:
      - ./:/app
